Algoritmo "Atividade 2 - tipo de dados"
// Disciplina  : criação de aplicações e Sistemas
// Professor: Franklin Portela
// Descrição:Algoritimo para atividade 2
// Autor(a): Wanderson Pereira
// Data atual: 6/5/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Tipo de caracter: Tiago")
escreval("Tipo de inteiro:", 28)
escreval("Tipo de real:", 1,68)
escreval("Tipo de booleanos:", verdadeiro)

Fimalgoritmo