Algoritmo "Atividade 8 - Matriz"
// Disciplina: Criação de aplicações e sistemas
// Professor: Franklin Portela
// Descrição: Algoritimo para atividade 8
// Autor(a): Wanderson Pereira
// Data atual: 8/5/2022

Var
// Seção de Declarações das variáveis

num:vetor[1..5,1..5] de inteiro
l,c:inteiro
s:inteiro

Inicio
// Leitura dos dados .

s<-0
para l de 1 ate 5 faca
 para c de 1 ate 5 faca
  s<-s+10
  num [l,c]<-s
 fimpara
 
 escreval([i,j])
 
fimpara

Fimalgoritmo